# -*- coding: utf-8 -*-
"""B1910202-Lab6-missing-values-basic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10bYpSZL8MY9-m-mk1sG8qWGTLtQOQUY0
"""

import pandas as pd
import numpy as np

df = pd.read_excel("https://github.com/ltdaovn/dataset/blob/master/student.xlsx?raw=true", index_col='id')
print(df)

# Xóa các hàng có bất kỳ giá trị nào bị rỗng
new_df = df.dropna(axis=0, how='any', inplace=False)
print(new_df)

# Xóa các hàng có tất cả giá trị đều bị rỗng
new_df = df.dropna(axis=0, inplace=False)
print(new_df)

# Xóa các cột có bất kỳ giá trị nào bị rỗng
new_df = df.dropna(axis=1, how='any', inplace=False)
print(new_df)

# Xóa các cột có tất cả giá trị đều bị rỗng
new_df = df.dropna(axis=1, inplace=False)
print(new_df)

# Chỉ giữ lại các hàng có từ 2 dữ liệu hợp lệ trở lên
new_df = df.dropna(thresh=2)
print(new_df)

# Chỉ giữ lại các hàng có từ 3 dữ liệu hợp lệ trở lên
new_df = df.dropna(thresh=3)
print(new_df)

# Chỉ giữ lại các cột có từ 11 dữ liệu hợp lệ
new_df = df.dropna(axis=1, thresh=11)
print(new_df)

# Chỉ giữ lại các hàng có 70% dữ liệu hợp lệ trở lên
new_df = df.dropna(how='any',axis=0,thresh=df.shape[1]*0.7)
print(new_df)

#Chỉ giữ lại các cột có 80% dữ liệu hợp lệ trở lên
new_df = df.dropna(how='any',axis=1,thresh=df.shape[1]*0.8)
print(new_df)